### ISSUE TITLE
Serveur ?

### ISSUE THREAD

**Issue by S73ph4n** [AmarOk1412/RORIV2#1]
Impossible de localiser les sources pour compiler le serveur. Dans le repo, le dossier correspondant apparait vide.

**Comment by AmarOk1412** [comment]
Oublié d'enlever ce repo. Je te dirige vers la vraie version :  https://github.com/AmarOk1412/RORI
Le serveur a été enlevé pour n'avoir que RORI qui fait la partie serveur + un client (Desktop/Android selon ton choix). Désolé de la confusion avec le V2

**Comment by S73ph4n** [comment]
Merci !
